In [ ]:
l = """https://github.com/dipampaul17/AgentGuard
https://github.com/truffle-ai/dexto
https://github.com/traceroot-ai/traceroot
https://github.com/lastmile-ai/mcp-agent/tree/main/examples/usecases/mcp_realtor_agent
https://github.com/fal-ai-community/video-starter-kit
https://github.com/plandex-ai/plandex
https://github.com/matiasmolinas/evolving-agents
https://github.com/Operative-Sh/web-eval-agent
https://github.com/TabbyML/tabby
https://github.com/1rvinn/mindpalace
https://github.com/kody-w/Copilot-Agent-365
https://github.com/KittenML/KittenTTS
https://github.com/JackHopkins/factorio-learning-environment
https://github.com/DIYer22/discrete_distribution_networks
https://github.com/nari-labs/dia
https://github.com/EpicenterHQ/epicenter/tree/main/apps/whispering
https://github.com/KoljaB/RealtimeVoiceChat
https://github.com/circlemind-ai/fast-graphrag
https://github.com/onlook-dev/onlook
https://github.com/codelion/pts
https://github.com/brianmg/voynich-nlp-analysis
https://github.com/abhinavxd/libredesk
https://github.com/browserbase/stagehand
https://github.com/lastmile-ai/mcp-agent"""

In [ ]:
list_of_urls = l.split("\n")

In [ ]:
import os
for i in list_of_urls:
    os.system(f'git clone {i}')

In [ ]:
json_file = '/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/descriptions_for_clustered_communities_v2.json'
import json
new_l = []
with open(json_file, 'r') as f:
    data = json.load(f)
    for file in data:
        data[file]['community_count'] = len(data[file]['descriptions'].split('\n\n'))
        new_l.append(data[file])

In [ ]:
json.dump(new_l, open('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/descriptions_list_v2.json', 'w'))

In [ ]:
import pandas as pd
forecast_df = pd.read_csv("/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/experiments-llm/results/pattern_embeddings/gemini_communities_embedding_classified_merged_predictions.csv")
verified_df = pd.read_csv("/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/experiments-llm/inputs/AI Pattern Project_ Results - Verified Communities.csv")

In [ ]:
forecast_df.head()

In [ ]:
verified_df['Code file'] = verified_df['Code file'].str.replace("https://github.com/HasinthakaPiyumal/AI-Pattern-Mining-Project/blob/main/notebooks/result/repo_callgraph_clusters/","")

In [ ]:
verified_df['code summary'] = verified_df['Code file'].apply(lambda x: forecast_df[forecast_df['file']==x]['code summary'].values[0] if x in forecast_df['file'].values else "")
verified_df['NN forecasted'] = verified_df['Code file'].apply(lambda x: forecast_df[forecast_df['file']==x]['nn prediction'].values[0] if x in forecast_df['file'].values else "")
verified_df['LR forecasted'] = verified_df['Code file'].apply(lambda x: forecast_df[forecast_df['file']==x]['logreg prediction'].values[0] if x in forecast_df['file'].values else "")

In [ ]:
verified_df.drop(columns=['Column 3']).to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/experiments-llm/inputs/AI Pattern Project_ Results - Verified Communities Enriched.csv', index=False)

In [ ]:
verified_df

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
    'c': [1,2,3,4,5],
    'b': [5,4,3,2,1],
    'a': [2,3,4,5,6]
})

df2 = pd.DataFrame({
    'a': [5,4,3,2,1],
    'b': [1,2,3,4,5],
    'c': [6,5,4,3,2]
})

In [ ]:
df1

In [ ]:
df2

In [ ]:
max_vals = pd.DataFrame()
# max val per class per column
for row in df1.iterrows():
    for col in df1.columns:
        max_vals.at[row[0], col] = max(row[1][col], df2.at[row[0], col])

In [ ]:
max_vals

In [9]:
import pandas as pd

prediction_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/src/stages/pattern_classification/unverified_weighted_predictions.csv')
prediction_df.fillna('None Type', inplace=True)

In [10]:
prediction_df['weighted_pred'].value_counts()

weighted_pred
none                                         616
Forecasting with Classical Models            516
LLM-based Multimodal Generative Prompting    487
Preprocessing Text and Numerical Data        379
Using Tools with LLMs                        147
Retrieval Augmented Generation(RAG)          144
Agent Architecture                           139
Model Abstraction                            104
Name: count, dtype: int64

In [1]:
import pandas as pd

prediction_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/src/stages/pattern_classification/ensemble_classification_predictions.csv')
prediction_df.fillna('None Type', inplace=True)

In [5]:
prediction_df['weighted_pred'].value_counts()

weighted_pred
Forecasting with Classical Models            72
none                                         63
LLM-based Multimodal Generative Prompting    60
Preprocessing Text and Numerical Data        47
Retrieval Augmented Generation(RAG)          29
Using Tools with LLMs                        25
Model Abstraction                            21
Agent Architecture                           13
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import classification_report

print("Threshold Based Model Classification Report:")
display(pd.DataFrame(classification_report(prediction_df['pattern'], prediction_df['threshold_class'],output_dict=True, zero_division=0)).T)
print("No Threshold Model Classification Report:")
display(pd.DataFrame(classification_report(prediction_df['pattern'], prediction_df['without_threshold_class'],output_dict=True, zero_division=0)).T)
print("Second Level Model (LR) Classification Report:")
display(pd.DataFrame(classification_report(prediction_df['pattern'], prediction_df['second_level_model_class_lr'],output_dict=True, zero_division=0)).T)
print("Second Level Model (RR) Classification Report:")
display(pd.DataFrame(classification_report(prediction_df['pattern'], prediction_df['second_level_model_class_rr'],output_dict=True, zero_division=0)).T)

In [ ]:
import json
discriptions = json.load(open('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/predicted_clusters_verification_results_with_descriptions.json'))

In [ ]:
import json
patterns = json.load(open('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/cluster_results/curated_clusters_nov25.json'))

In [ ]:
for i in patterns:
    print(f"{i['short_name']}")
    for j in i['l2_patterns']:
        print(f" - {j}")

In [5]:
old_to_new_mapping = {
    "Advanced LLM Prompting": "Advanced LLM Prompting",
    "Classical Models": "Forecasting with Classical Models",
    "Enhanced User Intent Comprehension with LLMs": "LLM-based User Intent Extraction",
    "LLM Agent Training & Alignment": "LLM Fine-Tuning, Training & Alignment",
    "LLM Context Management": "LLM-based Context Management",
    "LLM Results Evaluation": "Evaluating LLM Results",
    "LLM based Multimodal Generative Prompting": "LLM-based Multimodal Generative Prompting",
    "LLM based Planning, Iterative Optimizations and ReAct, or Reasoning, Think Step by step, XoT":
        "LLM-based Planning, XoT, ReAct, or Reasoning",
    "Model Abstraction Pattern": "Model Abstraction",
    "Modular LLM Agent Architectures": "Agent Architecture",
    "None": "None",
    "Preprocessing Text and Numerical Data": "Preprocessing Text and Numerical Data",
    "Reliable, Transparent, & Augmented LLMs":
        "Enabling Reliability, Explainability, or Robustness",
    "Retrieval Augmented Generation(RAG) Optimization for LLMs":
        "Retrieval Augmented Generation(RAG)",
    "Structured Output & Formatting for LLMs":
        "Performing Structured Output & Formatting for LLMs",
    "Tool Use for LLMs": "Using Tools with LLMs"
}

In [ ]:
import pandas as pd

data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')

In [ ]:
data['verified_pattern'] = data['verified_pattern'].apply(lambda x: old_to_new_mapping.get(x, x))
data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')

In [ ]:
data['verified_pattern'].value_counts()

In [ ]:
data['verified_pattern'].value_counts()

### Combining labeled data

In [ ]:
labeled_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')
newly_verified = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/AI Pattern Project_ Results - Algorithemic Sampling - 100 [jan 20].csv')

verified_map = {file:pattern for file, pattern in zip(newly_verified['file'], newly_verified['verified_pattern'])}

labeled_data['verified_pattern'] = labeled_data['file'].apply(lambda x: verified_map.get(x, labeled_data[labeled_data['file']==x]['verified_pattern'].values[0]))
labeled_data['verified'] = labeled_data['verified_pattern'].notna()

labeled_data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv', index=False)

In [1]:
import pandas as pd
labeled_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')

In [10]:
labeled_data['verified_pattern'].value_counts()

verified_pattern
none                                                   64
Forecasting with Classical Models                      64
LLM-based Multimodal Generative Prompting              52
Preprocessing Text and Numerical Data                  51
Using Tools with LLMs                                  31
Retrieval Augmented Generation(RAG)                    28
Model Abstraction                                      20
Agent Architecture                                     20
Evaluating LLM Results                                 18
MLOps                                                  18
Advanced LLM Prompting                                 14
LLM-based Planning, XoT, ReAct, or Reasoning           12
Enabling Reliability, Explainability, or Robustness     8
LLM-based User Intent Extraction                        8
LLM Fine-Tuning, Training & Alignment                   4
LLM-based Context Management                            1
Name: count, dtype: int64

In [3]:
updated_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/AI Pattern Project_ Results - all-communities 413 (1).csv')
updated_data['verified_pattern'].value_counts()

verified_pattern
none                                                   85
Forecasting with Classical Models                      63
LLM-based Multimodal Generative Prompting              52
Preprocessing Text and Numerical Data                  50
Using Tools with LLMs                                  31
Retrieval Augmented Generation(RAG)                    28
Agent Architecture                                     20
Model Abstraction                                      20
Evaluating LLM Results                                 18
Advanced LLM Prompting                                 14
LLM-based Planning, XoT, ReAct, or Reasoning           12
Enabling Reliability, Explainability, or Robustness     8
LLM-based User Intent Extraction                        8
LLM Fine-Tuning, Training & Alignment                   4
Name: count, dtype: int64

In [6]:
updated_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/AI Pattern Project_ Results - all-communities 413 JAN 26.csv')
updated_data = updated_data.drop('Unnamed: 0',errors='ignore')
updated_data['verified_pattern'] = updated_data['verified_pattern'].apply(lambda x: old_to_new_mapping.get(x, x))
verified_map = {file:pattern for file, pattern in zip(updated_data['file'], updated_data['verified_pattern'])}

In [7]:
labeled_data['verified_pattern'] = labeled_data['file'].apply(lambda x: verified_map.get(x, labeled_data[labeled_data['file']==x]['verified_pattern'].values[0]))

In [11]:
labeled_data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv', index=False)

In [8]:
sum(labeled_data['verified_pattern'].value_counts())

413

### class diff

In [25]:
import pandas as pd

old_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/AI Pattern Project_ Results - all-communities 413.csv')
new_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/AI Pattern Project_ Results - all-communities 413 (1).csv')

In [29]:
old_df['verified_pattern'].value_counts()

verified_pattern
none                                                         80
Forecasting with Classical Models                            56
Preprocessing Text and Numerical Data                        50
LLM-based Multimodal Generative Prompting                    49
Using Tools with LLMs                                        30
Retrieval Augmented Generation(RAG)                          23
Agent Architecture                                           19
Model Abstraction                                            18
Evaluating LLM Results                                       13
LLM-based Planning, XoT, ReAct, or Reasoning                 12
Advanced LLM Prompting                                       10
LLM-based User Intent Extraction                              8
Enabling Reliability, Explainability, or Robustness           8
Classical Models                                              7
Performing Structured Output & Formatting for LLMs            6
LLM Results Evaluation                                        5
Integrating External Knlowladge with LLM                      4
LLM Fine-Tuning, Training & Alignment                         4
LLM based Multimodal Generative Prompting                     3
LLM-based Context Management                                  2
Model Abstraction Pattern                                     2
LLM Context Management                                        1
Modular LLM Agent Architectures                               1
Retrieval Augmented Generation(RAG) Optimization for LLMs     1
Tool Use for LLMs                                             1
Name: count, dtype: int64

In [31]:
new_df['verified_pattern'].value_counts()

verified_pattern
none                                                   85
Forecasting with Classical Models                      63
LLM-based Multimodal Generative Prompting              52
Preprocessing Text and Numerical Data                  50
Using Tools with LLMs                                  31
Retrieval Augmented Generation(RAG)                    28
Agent Architecture                                     20
Model Abstraction                                      20
Evaluating LLM Results                                 18
Advanced LLM Prompting                                 14
LLM-based Planning, XoT, ReAct, or Reasoning           12
Enabling Reliability, Explainability, or Robustness     8
LLM-based User Intent Extraction                        8
LLM Fine-Tuning, Training & Alignment                   4
Name: count, dtype: int64

In [32]:
pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/models/class_thresholds1768974456.csv')

,Unnamed: 0,Advanced LLM Prompting,Agent Architecture,Evaluating LLM Results,Forecasting with Classical Models,LLM-based Multimodal Generative Prompting,"LLM-based Planning, XoT, ReAct, or Reasoning",Model Abstraction,Preprocessing Text and Numerical Data,Retrieval Augmented Generation(RAG),Using Tools with LLMs
0,0.00,0.250000,0.444444,0.333333,0.740741,0.583333,0.500000,0.333333,0.444444,0.545455,0.461538
1,0.05,0.285714,0.000000,0.400000,0.740741,0.608696,0.666667,0.333333,0.533333,0.600000,0.444444
2,0.10,0.333333,0.000000,0.400000,0.740741,0.666667,1.000000,0.400000,0.571429,0.750000,0.500000
3,0.15,0.333333,0.000000,0.400000,0.740741,0.700000,1.000000,0.400000,0.615385,0.857143,0.500000
4,0.20,0.500000,0.000000,0.000000,0.740741,0.736842,1.000000,0.500000,0.666667,0.857143,0.500000
5,0.25,0.500000,0.000000,0.000000,0.750000,0.800000,1.000000,0.500000,0.727273,0.857143,0.500000
6,0.30,0.500000,0.000000,0.000000,0.782609,0.800000,1.000000,0.500000,0.727273,0.857143,0.333333
7,0.35,0.500000,0.000000,0.000000,0.818182,0.800000,1.000000,0.500000,0.727273,0.857143,0.000000
8,0.40,0.500000,0.000000,0.000000,0.842105,0.857143,1.000000,0.500000,0.571429,0.857143,0.000000
9,0.45,0.500000,0.000000,0.000000,0.842105,0.857143,NaN,0.500000,0.571429,0.857143,0.000000
10,0.50,0.500000,0.000000,NaN,0.888889,0.923077,NaN,0.500000,0.666667,0.857143,0.000000

## Final

In [ ]:
import pandas as pd

labeled_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')
labeled_data = labeled_data[~labeled_data['verified_pattern'].isna()]

predictions = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/unverified_weighted_predictions.csv')

In [8]:
all_data = pd.concat([labeled_data[['file', 'verified_pattern']], predictions[['file', 'verified_pattern']]], ignore_index=True, sort=False)

In [7]:
predictions['verified_pattern'].value_counts()

verified_pattern
none                                         369
Forecasting with Classical Models            259
LLM-based Multimodal Generative Prompting    246
Preprocessing Text and Numerical Data        166
Retrieval Augmented Generation(RAG)           71
Using Tools with LLMs                         61
Agent Architecture                            60
Model Abstraction                             34
Name: count, dtype: int64

In [9]:
all_data['verified_pattern'].value_counts()

verified_pattern
none                                                   454
Forecasting with Classical Models                      322
LLM-based Multimodal Generative Prompting              298
Preprocessing Text and Numerical Data                  216
Retrieval Augmented Generation(RAG)                     99
Using Tools with LLMs                                   92
Agent Architecture                                      80
Model Abstraction                                       54
Evaluating LLM Results                                  18
Advanced LLM Prompting                                  14
LLM-based Planning, XoT, ReAct, or Reasoning            12
LLM-based User Intent Extraction                         8
Enabling Reliability, Explainability, or Robustness      8
LLM Fine-Tuning, Training & Alignment                    4
Name: count, dtype: int64

In [10]:
labeled_data['verified_pattern'].value_counts()

verified_pattern
none                                                   85
Forecasting with Classical Models                      63
LLM-based Multimodal Generative Prompting              52
Preprocessing Text and Numerical Data                  50
Using Tools with LLMs                                  31
Retrieval Augmented Generation(RAG)                    28
Model Abstraction                                      20
Agent Architecture                                     20
Evaluating LLM Results                                 18
Advanced LLM Prompting                                 14
LLM-based Planning, XoT, ReAct, or Reasoning           12
LLM-based User Intent Extraction                        8
Enabling Reliability, Explainability, or Robustness     8
LLM Fine-Tuning, Training & Alignment                   4
Name: count, dtype: int64

In [28]:
all_data['community-id'] = all_data['file'].apply(lambda x: x.split('/')[-2]+'/'+x.split('/')[-1])

In [29]:
all_data.head()

,file,verified_pattern,repo,community-id
0,https://github.com/HasinthakaPiyumal/AI-Patter...,LLM-based Multimodal Generative Prompting,3DOD_thesis,3DOD_thesis/cluster_0.py
1,https://github.com/HasinthakaPiyumal/AI-Patter...,none,3DOD_thesis,3DOD_thesis/cluster_1.py
2,https://github.com/HasinthakaPiyumal/AI-Patter...,LLM-based Multimodal Generative Prompting,3DOD_thesis,3DOD_thesis/cluster_10.py
3,https://github.com/HasinthakaPiyumal/AI-Patter...,Preprocessing Text and Numerical Data,3DOD_thesis,3DOD_thesis/cluster_3.py
4,https://github.com/HasinthakaPiyumal/AI-Patter...,none,3DOD_thesis,3DOD_thesis/cluster_4.py

In [30]:
all_data[['community-id', 'verified_pattern']].to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/final_verified_patterns.csv', index=False)
all_data[['repo','community-id']].to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/temp/repo_community_ids.csv', index=False)

In [ ]:
all_data['repo'] = all_data['file'].apply(lambda x: x.split('/')[-2])
grouped_data = pd.DataFrame()
for group in all_data.groupby('repo'):
    print(f"{group[0]}: {len(group[1])}")
    for pattern, count in group[1]['verified_pattern'].value_counts().items():
        grouped_data.at[group[0], pattern] = count


display(grouped_data)

3DOD_thesis: 11
AIlice: 39
AgentBench: 21
ArxivDigest: 4
Automatic_Speech_Recognition: 19
Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning: 9
BruteForceAI: 5
CAAFE: 9
ChatSim: 163
Copilot-Agent-365: 5
CyberScraper-2077: 10
DI-sheep: 3
DLTA-AI: 113
DRL-Pytorch: 7
DeepLearning-IDS: 2
EvoAgentX: 63
FinceptTerminal: 39
FuxiCTR: 12
GPT_Vuln-analyzer: 11
GoBigger: 15
HackBot: 1
HuixiangDou: 40
KittenTTS: 1
MIRNetv2: 16
MassGen: 28
MiniMax-M1: 5
Octopii: 3
OpenLearning4DeepRecsys: 5
PentestAgent: 6
PointTransformerV2: 19
RLMRec: 13
RealtimeVoiceChat: 6
Reinforcement_Learning_in_Python: 5
SimBiber: 1
Stride-AI-Agents: 6
VectorizedMultiAgentSimulator: 26
WebShop: 16
YOLO3D: 24
adaptive-classifier: 10
build_MiniLLM_from_scratch: 3
chipper: 9
clai: 37
crafter: 1
dalle-flow: 1
deep_recommenders: 7
dia: 7
discrete_distribution_networks: 14
drl_grasping: 18
evadb: 64

evolving-agents: 12
factorio-learning-environment: 72
fast-graphrag: 14
jodie: 1
ladi-vton: 8
mAP: 2
mahalanobis_3d_multi_object_tracking: 9
mcp-agent: 60
mindpalace: 4
monkey-net: 12
multi-class-text-classification-cnn: 2
nuplan-devkit: 141
oasis: 13
optillm: 50
pomdp-baselines: 20
pts: 4
pybroker: 20
pytorch_RVAE: 3
scattertext: 64
semantic-router: 27
surpriver: 2
synthetic-data-generator: 51
tabby: 5
tf.fashionAI: 17
tf.gans-comparison: 7
torchio: 25
traceroot: 20
transfuser: 27
v2x-vit: 17
vigil-llm: 8
viral-clips-crew: 7
web-eval-agent: 3

,LLM-based Multimodal Generative Prompting,Preprocessing Text and Numerical Data,none,Using Tools with LLMs,Model Abstraction,Agent Architecture,"LLM Fine-Tuning, Training & Alignment",Evaluating LLM Results,Retrieval Augmented Generation(RAG),LLM-based User Intent Extraction,"LLM-based Planning, XoT, ReAct, or Reasoning",Forecasting with Classical Models,"Enabling Reliability, Explainability, or Robustness",Advanced LLM Prompting
3DOD_thesis,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AIlice,9.0,1.0,9.0,8.0,5.0,4.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
AgentBench,NaN,7.0,4.0,4.0,NaN,1.0,1.0,1.0,NaN,2.0,1.0,NaN,NaN,NaN
ArxivDigest,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
Automatic_Speech_Recognition,3.0,7.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
transfuser,4.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN
v2x-vit,15.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
vigil-llm,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,6.0,1.0,NaN,NaN,NaN,NaN
viral-clips-crew,5.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
web-eval-agent,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
grouped_data.fillna(0, inplace=True)

In [21]:
#conver to int
grouped_data = grouped_data.astype(int)
grouped_data['total_patterns'] = 0
grouped_data['total_patterns'] = grouped_data.sum(axis=1) - grouped_data['none']
grouped_data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/pattern_counts_per_repo.csv')
display(grouped_data)

,LLM-based Multimodal Generative Prompting,Preprocessing Text and Numerical Data,none,Using Tools with LLMs,Model Abstraction,Agent Architecture,"LLM Fine-Tuning, Training & Alignment",Evaluating LLM Results,Retrieval Augmented Generation(RAG),LLM-based User Intent Extraction,"LLM-based Planning, XoT, ReAct, or Reasoning",Forecasting with Classical Models,"Enabling Reliability, Explainability, or Robustness",Advanced LLM Prompting,total_patterns
3DOD_thesis,4,4,3,0,0,0,0,0,0,0,0,0,0,0,8
AIlice,9,1,9,8,5,4,1,1,1,0,0,0,0,0,30
AgentBench,0,7,4,4,0,1,1,1,0,2,1,0,0,0,17
ArxivDigest,0,3,0,0,0,0,0,0,1,0,0,0,0,0,4
Automatic_Speech_Recognition,3,7,3,0,0,0,0,0,0,0,0,5,1,0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
transfuser,4,0,19,0,0,0,0,0,0,0,1,3,0,0,8
v2x-vit,15,0,1,0,0,0,0,0,0,0,0,1,0,0,16
vigil-llm,0,0,1,0,0,0,0,0,6,1,0,0,0,0,7
viral-clips-crew,5,0,1,0,0,0,0,0,1,0,0,0,0,0,6
web-eval-agent,0,0,1,1,0,1,0,0,0,0,0,0,0,0,2

In [1]:
import pandas as pd
import os

In [5]:
repos = pd.read_json('/home/hasinthaka/Documents/Experiments/Pattern Extraction - From Repos/data/finalized-repost.json')

0     https://github.com/jiegzhan/multi-class-text-c...
1                    https://github.com/claws-lab/jodie
2                https://github.com/AutoLLM/ArxivDigest
3     https://github.com/Fincept-Corporation/Fincept...
4              https://github.com/kefirski/pytorch_RVAE
                            ...
71               https://github.com/redhuntlabs/Octopii
72    https://github.com/vinayakumarr/Network-Intrus...
73            https://github.com/motional/nuplan-devkit
74             https://github.com/MorDavid/BruteForceAI
75               https://github.com/LucasAlegre/sumo-rl
Name: svn_url, Length: 76, dtype: object

In [9]:
pd.DataFrame(repos['svn_url'].values, columns=['directory']).to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_cluster_directories.csv', index=False)

In [14]:
pd.DataFrame(pd.read_csv('/home/hasinthaka/Documents/Projects/AI/repo-list.csv')['https://github.com/jiegzhan/multi-class-text-classification-cnn'].unique()).to_csv('/home/hasinthaka/Documents/Projects/AI/unique-repo-list.csv', index=False)

### Code , label pair

In [1]:
import pandas as pd
labeled_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')

In [2]:
labeled_data['path'] = labeled_data['file'].apply(lambda x: f'/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/{x.split("/")[-2]}/{x.split("/")[-1]}')

In [3]:
labeled_data

,Unnamed: 0,verified_pattern,code_summary,verified,file,path
0,0,LLM-based Multimodal Generative Prompting,This code implements a data pipeline for 3D ob...,True,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
1,1,none,This code implements a 3D object pose estimati...,True,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
2,2,LLM-based Multimodal Generative Prompting,This code defines data pipelines for 3D object...,True,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
3,3,NaN,This code implements a recursive pattern for *...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
4,4,Preprocessing Text and Numerical Data,This code implements an **angular discretizati...,True,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
...,...,...,...,...,...,...
1674,1674,NaN,This code implements a robust pattern for mana...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
1675,1675,NaN,This code exemplifies an AI pattern focused on...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
1676,1676,NaN,The code implements an **AI Agent Control** pa...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
1677,1677,NaN,The provided code primarily consists of utilit...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...
1678,1678,NaN,This code implements an **Agent Output Parsing...,False,https://github.com/HasinthakaPiyumal/AI-Patter...,/home/hasinthaka/Documents/Projects/AI/Pattern...

In [4]:
def load_code(file_path):
    try:
        print(file_path)
        with open(file_path, 'r') as f:
            return f.read()
    except:
        return ""

In [6]:
load_code(labeled_data.iloc[0]['path'])

/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_0.py

"# Cluster 0\n\ndef getBinNumber(angle, NH):\n    if NH == 4:\n        return getBinNumber4(angle)\n    else:\n        raise Exception('getBinNumber: NH is not 4')\n\nclass EvalDatasetFrustumPointNetImg(torch.utils.data.Dataset):\n\n    def __init__(self, kitti_data_path, kitti_meta_path, type, NH):\n        self.img_dir = kitti_data_path + '/object/training/image_2/'\n        self.label_dir = kitti_data_path + '/object/training/label_2/'\n        self.calib_dir = kitti_data_path + '/object/training/calib/'\n        self.lidar_dir = kitti_data_path + '/object/training/velodyne/'\n        self.NH = NH\n        with open(kitti_meta_path + '/%s_img_ids.pkl' % type, 'rb') as file:\n            img_ids = pickle.load(file)\n        with open(kitti_meta_path + '/kitti_train_mean_car_size.pkl', 'rb') as file:\n            self.mean_car_size = pickle.load(file)\n        with open(kitti_meta_path + '/kitti_centered_frustum_mean_xyz.pkl', 'rb') as file:\n            self.centered_frustum_mean_xyz = pickle.load(file)\n            self.centered_frustum_mean_xyz = self.centered_frustum_mean_xyz.astype(np.float32)\n        self.examples = []\n        for img_id in img_ids:\n            labels = LabelLoader2D3D(img_id, self.label_dir, '.txt', self.calib_dir, '.txt')\n            for label in labels:\n                label_2d = label['label_2D']\n                if label_2d['truncated'] < 0.5 and label_2d['class'] == 'Car':\n                    label['img_id'] = img_id\n                    self.examples.append(label)\n        self.num_examples = len(self.examples)\n\n    def __getitem__(self, index):\n        example = self.examples[index]\n        img_id = example['img_id']\n        lidar_path = self.lidar_dir + img_id + '.bin'\n        point_cloud = np.fromfile(lidar_path, dtype=np.float32).reshape(-1, 4)\n        orig_point_cloud = point_cloud\n        point_cloud = point_cloud[point_cloud[:, 0] > 0, :]\n        point_cloud = point_cloud[point_cloud[:, 0] < 80, :]\n        calib = calibread(self.calib_dir + img_id + '.txt')\n        P2 = calib['P2']\n        Tr_velo_to_cam_orig = calib['Tr_velo_to_cam']\n        R0_rect_orig = calib['R0_rect']\n        R0_rect = np.eye(4)\n        R0_rect[0:3, 0:3] = R0_rect_orig\n        Tr_velo_to_cam = np.eye(4)\n        Tr_velo_to_cam[0:3, :] = Tr_velo_to_cam_orig\n        point_cloud_xyz = point_cloud[:, 0:3]\n        point_cloud_xyz_hom = np.ones((point_cloud.shape[0], 4))\n        point_cloud_xyz_hom[:, 0:3] = point_cloud[:, 0:3]\n        img_points_hom = np.dot(P2, np.dot(R0_rect, np.dot(Tr_velo_to_cam, point_cloud_xyz_hom.T))).T\n        img_points = np.zeros((img_points_hom.shape[0], 2))\n        img_points[:, 0] = img_points_hom[:, 0] / img_points_hom[:, 2]\n        img_points[:, 1] = img_points_hom[:, 1] / img_points_hom[:, 2]\n        point_cloud_xyz_camera_hom = np.dot(R0_rect, np.dot(Tr_velo_to_cam, point_cloud_xyz_hom.T)).T\n        point_cloud_xyz_camera = np.zeros((point_cloud_xyz_camera_hom.shape[0], 3))\n        point_cloud_xyz_camera[:, 0] = point_cloud_xyz_camera_hom[:, 0] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_xyz_camera[:, 1] = point_cloud_xyz_camera_hom[:, 1] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_xyz_camera[:, 2] = point_cloud_xyz_camera_hom[:, 2] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_camera = point_cloud\n        point_cloud_camera[:, 0:3] = point_cloud_xyz_camera\n        label_2D = example['label_2D']\n        label_3D = example['label_3D']\n        bbox = label_2D['poly']\n        u_min = bbox[0, 0]\n        u_max = bbox[1, 0]\n        v_min = bbox[0, 1]\n        v_max = bbox[2, 1]\n        u_min_expanded = u_min\n        u_max_expanded = u_max\n        v_min_expanded = v_min\n        v_max_expanded = v_max\n        input_2Dbbox = np.array([u_min_expanded, u_max_expanded, v_min_expanded, v_max_expanded])\n        row_mask = np.logical_and(np.logical_and(img_points[:, 0] >= u_min_expanded, img_points[:, 0] <= u_max_expanded), np.logical_and(img_points[:, 1] >= v_min_expanded, img_points[:, 1] <= v_max_expanded))\n        frustum_point_cloud_xyz = point_cloud_xyz[row_mask, :]\n        frustum_point_cloud = point_cloud[row_mask, :]\n        frustum_point_cloud_xyz_camera = point_cloud_xyz_camera[row_mask, :]\n        frustum_point_cloud_camera = point_cloud_camera[row_mask, :]\n        if frustum_point_cloud.shape[0] == 0:\n            print(img_id)\n            print(frustum_point_cloud.shape)\n            return self.__getitem__(0)\n        if frustum_point_cloud.shape[0] < 1024:\n            row_idx = np.random.choice(frustum_point_cloud.shape[0], 1024, replace=True)\n        else:\n            row_idx = np.random.choice(frustum_point_cloud.shape[0], 1024, replace=False)\n        frustum_point_cloud_xyz = frustum_point_cloud_xyz[row_idx, :]\n        frustum_point_cloud = frustum_point_cloud[row_idx, :]\n        frustum_point_cloud_xyz_camera = frustum_point_cloud_xyz_camera[row_idx, :]\n        frustum_point_cloud_camera = frustum_point_cloud_camera[row_idx, :]\n        img_path = self.img_dir + img_id + '.png'\n        img = cv2.imread(img_path, -1)\n        bbox_2d_img = img[int(np.max([0, v_min])):int(v_max), int(np.max([0, u_min])):int(u_max)]\n        bbox_2d_img = cv2.resize(bbox_2d_img, (224, 224))\n        points = label_3D['points']\n        y_max = points[0, 1]\n        y_min = points[4, 1]\n        A = np.array([points[0, 0], points[0, 2]])\n        B = np.array([points[1, 0], points[1, 2]])\n        D = np.array([points[3, 0], points[3, 2]])\n        AB = B - A\n        AD = D - A\n        AB_dot_AB = np.dot(AB, AB)\n        AD_dot_AD = np.dot(AD, AD)\n        P = np.zeros((frustum_point_cloud_xyz_camera.shape[0], 2))\n        P[:, 0] = frustum_point_cloud_xyz_camera[:, 0]\n        P[:, 1] = frustum_point_cloud_xyz_camera[:, 2]\n        AP = P - A\n        AP_dot_AB = np.dot(AP, AB)\n        AP_dot_AD = np.dot(AP, AD)\n        row_mask = np.logical_and(np.logical_and(frustum_point_cloud_xyz_camera[:, 1] >= y_min, frustum_point_cloud_xyz_camera[:, 1] <= y_max), np.logical_and(np.logical_and(AP_dot_AB >= 0, AP_dot_AB <= AB_dot_AB), np.logical_and(AP_dot_AD >= 0, AP_dot_AD <= AD_dot_AD)))\n        gt_point_cloud_xyz_camera = frustum_point_cloud_xyz_camera[row_mask, :]\n        label_InstanceSeg = np.zeros((frustum_point_cloud.shape[0],), dtype=np.int64)\n        label_InstanceSeg[row_mask] = 1\n        u_center = u_min_expanded + (u_max_expanded - u_min_expanded) / 2.0\n        v_center = v_min_expanded + (v_max_expanded - v_min_expanded) / 2.0\n        center_img_point_hom = np.array([u_center, v_center, 1])\n        P2_pseudo_inverse = np.linalg.pinv(P2)\n        point_hom = np.dot(P2_pseudo_inverse, center_img_point_hom)\n        point = np.array([point_hom[0] / point_hom[3], point_hom[1] / point_hom[3], point_hom[2] / point_hom[3]])\n        if point[2] < 0:\n            point[0] = -point[0]\n            point[2] = -point[2]\n        frustum_angle = np.arctan2(point[0], point[2])\n        frustum_R = np.asarray([[np.cos(frustum_angle), 0, -np.sin(frustum_angle)], [0, 1, 0], [np.sin(frustum_angle), 0, np.cos(frustum_angle)]], dtype='float32')\n        centered_frustum_point_cloud_xyz_camera = np.dot(frustum_R, frustum_point_cloud_xyz_camera.T).T\n        centered_frustum_point_cloud_xyz_camera -= self.centered_frustum_mean_xyz\n        centered_frustum_point_cloud_camera = frustum_point_cloud_camera\n        centered_frustum_point_cloud_camera[:, 0:3] = centered_frustum_point_cloud_xyz_camera\n        label_TNet = np.dot(frustum_R, label_3D['center']) - self.centered_frustum_mean_xyz\n        centered_r_y = wrapToPi(label_3D['r_y'] - frustum_angle)\n        bin_number = getBinNumber(centered_r_y, NH=self.NH)\n        bin_center = getBinCenter(bin_number, NH=self.NH)\n        residual = wrapToPi(centered_r_y - bin_center)\n        label_BboxNet = np.zeros((11,), dtype=np.float32)\n        label_BboxNet[0:3] = np.dot(frustum_R, label_3D['center']) - self.centered_frustum_mean_xyz\n        label_BboxNet[3] = label_3D['h']\n        label_BboxNet[4] = label_3D['w']\n        label_BboxNet[5] = label_3D['l']\n        label_BboxNet[6] = bin_number\n        label_BboxNet[7] = residual\n        label_BboxNet[8:] = self.mean_car_size\n        Rmat = np.asarray([[math.cos(residual), 0, math.sin(residual)], [0, 1, 0], [-math.sin(residual), 0, math.cos(residual)]], dtype='float32')\n        center = label_BboxNet[0:3]\n        l = label_3D['l']\n        w = label_3D['w']\n        h = label_3D['h']\n        p0 = center + np.dot(Rmat, np.asarray([l / 2.0, 0, w / 2.0], dtype='float32').flatten())\n        p1 = center + np.dot(Rmat, np.asarray([-l / 2.0, 0, w / 2.0], dtype='float32').flatten())\n        p2 = center + np.dot(Rmat, np.asarray([-l / 2.0, 0, -w / 2.0], dtype='float32').flatten())\n        p3 = center + np.dot(Rmat, np.asarray([l / 2.0, 0, -w / 2.0], dtype='float32').flatten())\n        p4 = center + np.dot(Rmat, np.asarray([l / 2.0, -h, w / 2.0], dtype='float32').flatten())\n        p5 = center + np.dot(Rmat, np.asarray([-l / 2.0, -h, w / 2.0], dtype='float32').flatten())\n        p6 = center + np.dot(Rmat, np.asarray([-l / 2.0, -h, -w / 2.0], dtype='float32').flatten())\n        p7 = center + np.dot(Rmat, np.asarray([l / 2.0, -h, -w / 2.0], dtype='float32').flatten())\n        label_corner = np.array([p0, p1, p2, p3, p4, p5, p6, p7])\n        label_corner_flipped = np.array([p2, p3, p0, p1, p6, p7, p4, p5])\n        bbox_2d_img = bbox_2d_img / 255.0\n        bbox_2d_img = bbox_2d_img - np.array([0.485, 0.456, 0.406])\n        bbox_2d_img = bbox_2d_img / np.array([0.229, 0.224, 0.225])\n        bbox_2d_img = np.transpose(bbox_2d_img, (2, 0, 1))\n        bbox_2d_img = bbox_2d_img.astype(np.float32)\n        centered_frustum_point_cloud_camera = torch.from_numpy(centered_frustum_point_cloud_camera)\n        bbox_2d_img = torch.from_numpy(bbox_2d_img)\n        label_InstanceSeg = torch.from_numpy(label_InstanceSeg)\n        label_TNet = torch.from_numpy(label_TNet)\n        label_BboxNet = torch.from_numpy(label_BboxNet)\n        label_corner = torch.from_numpy(label_corner)\n        label_corner_flipped = torch.from_numpy(label_corner_flipped)\n        return (centered_frustum_point_cloud_camera, bbox_2d_img, label_InstanceSeg, label_TNet, label_BboxNet, label_corner, label_corner_flipped, img_id, input_2Dbbox, frustum_R, frustum_angle, self.centered_frustum_mean_xyz)\n\n    def __len__(self):\n        return self.num_examples\n\nclass EvalSequenceDatasetFrustumPointNetImg(torch.utils.data.Dataset):\n\n    def __init__(self, kitti_data_path, kitti_meta_path, NH, sequence):\n        self.img_dir = kitti_data_path + '/tracking/training/image_02/' + sequence + '/'\n        self.lidar_dir = kitti_data_path + '/tracking/training/velodyne/' + sequence + '/'\n        self.label_path = kitti_data_path + '/tracking/training/label_02/' + sequence + '.txt'\n        self.calib_path = kitti_meta_path + '/tracking/training/calib/' + sequence + '.txt'\n        self.NH = NH\n        with open(kitti_meta_path + '/kitti_train_mean_car_size.pkl', 'rb') as file:\n            self.mean_car_size = pickle.load(file)\n        with open(kitti_meta_path + '/kitti_centered_frustum_mean_xyz.pkl', 'rb') as file:\n            self.centered_frustum_mean_xyz = pickle.load(file)\n            self.centered_frustum_mean_xyz = self.centered_frustum_mean_xyz.astype(np.float32)\n        img_ids = []\n        img_names = os.listdir(self.img_dir)\n        for img_name in img_names:\n            img_id = img_name.split('.png')[0]\n            img_ids.append(img_id)\n        self.examples = []\n        for img_id in img_ids:\n            if img_id.lstrip('0') == '':\n                img_id_float = 0.0\n            else:\n                img_id_float = float(img_id.lstrip('0'))\n            labels = LabelLoader2D3D_sequence(img_id, img_id_float, self.label_path, self.calib_path)\n            for label in labels:\n                label_2d = label['label_2D']\n                if label_2d['truncated'] < 0.5 and label_2d['class'] == 'Car':\n                    label['img_id'] = img_id\n                    self.examples.append(label)\n        self.num_examples = len(self.examples)\n\n    def __getitem__(self, index):\n        example = self.examples[index]\n        img_id = example['img_id']\n        lidar_path = self.lidar_dir + img_id + '.bin'\n        point_cloud = np.fromfile(lidar_path, dtype=np.float32).reshape(-1, 4)\n        orig_point_cloud = point_cloud\n        point_cloud = point_cloud[point_cloud[:, 0] > 0, :]\n        point_cloud = point_cloud[point_cloud[:, 0] < 80, :]\n        calib = calibread(self.calib_path)\n        P2 = calib['P2']\n        Tr_velo_to_cam_orig = calib['Tr_velo_to_cam']\n        R0_rect_orig = calib['R0_rect']\n        R0_rect = np.eye(4)\n        R0_rect[0:3, 0:3] = R0_rect_orig\n        Tr_velo_to_cam = np.eye(4)\n        Tr_velo_to_cam[0:3, :] = Tr_velo_to_cam_orig\n        point_cloud_xyz = point_cloud[:, 0:3]\n        point_cloud_xyz_hom = np.ones((point_cloud.shape[0], 4))\n        point_cloud_xyz_hom[:, 0:3] = point_cloud[:, 0:3]\n        img_points_hom = np.dot(P2, np.dot(R0_rect, np.dot(Tr_velo_to_cam, point_cloud_xyz_hom.T))).T\n        img_points = np.zeros((img_points_hom.shape[0], 2))\n        img_points[:, 0] = img_points_hom[:, 0] / img_points_hom[:, 2]\n        img_points[:, 1] = img_points_hom[:, 1] / img_points_hom[:, 2]\n        point_cloud_xyz_camera_hom = np.dot(R0_rect, np.dot(Tr_velo_to_cam, point_cloud_xyz_hom.T)).T\n        point_cloud_xyz_camera = np.zeros((point_cloud_xyz_camera_hom.shape[0], 3))\n        point_cloud_xyz_camera[:, 0] = point_cloud_xyz_camera_hom[:, 0] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_xyz_camera[:, 1] = point_cloud_xyz_camera_hom[:, 1] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_xyz_camera[:, 2] = point_cloud_xyz_camera_hom[:, 2] / point_cloud_xyz_camera_hom[:, 3]\n        point_cloud_camera = point_cloud\n        point_cloud_camera[:, 0:3] = point_cloud_xyz_camera\n        label_2D = example['label_2D']\n        label_3D = example['label_3D']\n        bbox = label_2D['poly']\n        u_min = bbox[0, 0]\n        u_max = bbox[1, 0]\n        v_min = bbox[0, 1]\n        v_max = bbox[2, 1]\n        u_min_expanded = u_min\n        u_max_expanded = u_max\n        v_min_expanded = v_min\n        v_max_expanded = v_max\n        input_2Dbbox = np.array([u_min_expanded, u_max_expanded, v_min_expanded, v_max_expanded])\n        row_mask = np.logical_and(np.logical_and(img_points[:, 0] >= u_min_expanded, img_points[:, 0] <= u_max_expanded), np.logical_and(img_points[:, 1] >= v_min_expanded, img_points[:, 1] <= v_max_expanded))\n        frustum_point_cloud_xyz = point_cloud_xyz[row_mask, :]\n        frustum_point_cloud = point_cloud[row_mask, :]\n        frustum_point_cloud_xyz_camera = point_cloud_xyz_camera[row_mask, :]\n        frustum_point_cloud_camera = point_cloud_camera[row_mask, :]\n        if frustum_point_cloud.shape[0] == 0:\n            print(img_id)\n            print(frustum_point_cloud.shape)\n            return self.__getitem__(0)\n        if frustum_point_cloud.shape[0] < 1024:\n            row_idx = np.random.choice(frustum_point_cloud.shape[0], 1024, replace=True)\n        else:\n            row_idx = np.random.choice(frustum_point_cloud.shape[0], 1024, replace=False)\n        frustum_point_cloud_xyz = frustum_point_cloud_xyz[row_idx, :]\n        frustum_point_cloud = frustum_point_cloud[row_idx, :]\n        frustum_point_cloud_xyz_camera = frustum_point_cloud_xyz_camera[row_idx, :]\n        frustum_point_cloud_camera = frustum_point_cloud_camera[row_idx, :]\n        img_path = self.img_dir + img_id + '.png'\n        img = cv2.imread(img_path, -1)\n        bbox_2d_img = img[int(np.max([0, v_min])):int(v_max), int(np.max([0, u_min])):int(u_max)]\n        bbox_2d_img = cv2.resize(bbox_2d_img, (224, 224))\n        points = label_3D['points']\n        y_max = points[0, 1]\n        y_min = points[4, 1]\n        A = np.array([points[0, 0], points[0, 2]])\n        B = np.array([points[1, 0], points[1, 2]])\n        D = np.array([points[3, 0], points[3, 2]])\n        AB = B - A\n        AD = D - A\n        AB_dot_AB = np.dot(AB, AB)\n        AD_dot_AD = np.dot(AD, AD)\n        P = np.zeros((frustum_point_cloud_xyz_camera.shape[0], 2))\n        P[:, 0] = frustum_point_cloud_xyz_camera[:, 0]\n        P[:, 1] = frustum_point_cloud_xyz_camera[:, 2]\n        AP = P - A\n        AP_dot_AB = np.dot(AP, AB)\n        AP_dot_AD = np.dot(AP, AD)\n        row_mask = np.logical_and(np.logical_and(frustum_point_cloud_xyz_camera[:, 1] >= y_min, frustum_point_cloud_xyz_camera[:, 1] <= y_max), np.logical_and(np.logical_and(AP_dot_AB >= 0, AP_dot_AB <= AB_dot_AB), np.logical_and(AP_dot_AD >= 0, AP_dot_AD <= AD_dot_AD)))\n        gt_point_cloud_xyz_camera = frustum_point_cloud_xyz_camera[row_mask, :]\n        label_InstanceSeg = np.zeros((frustum_point_cloud.shape[0],), dtype=np.int64)\n        label_InstanceSeg[row_mask] = 1\n        u_center = u_min_expanded + (u_max_expanded - u_min_expanded) / 2.0\n        v_center = v_min_expanded + (v_max_expanded - v_min_expanded) / 2.0\n        center_img_point_hom = np.array([u_center, v_center, 1])\n        P2_pseudo_inverse = np.linalg.pinv(P2)\n        point_hom = np.dot(P2_pseudo_inverse, center_img_point_hom)\n        point = np.array([point_hom[0] / point_hom[3], point_hom[1] / point_hom[3], point_hom[2] / point_hom[3]])\n        if point[2] < 0:\n            point[0] = -point[0]\n            point[2] = -point[2]\n        frustum_angle = np.arctan2(point[0], point[2])\n        frustum_R = np.asarray([[np.cos(frustum_angle), 0, -np.sin(frustum_angle)], [0, 1, 0], [np.sin(frustum_angle), 0, np.cos(frustum_angle)]], dtype='float32')\n        centered_frustum_point_cloud_xyz_camera = np.dot(frustum_R, frustum_point_cloud_xyz_camera.T).T\n        centered_frustum_point_cloud_xyz_camera -= self.centered_frustum_mean_xyz\n        centered_frustum_point_cloud_camera = frustum_point_cloud_camera\n        centered_frustum_point_cloud_camera[:, 0:3] = centered_frustum_point_cloud_xyz_camera\n        label_TNet = np.dot(frustum_R, label_3D['center']) - self.centered_frustum_mean_xyz\n        centered_r_y = wrapToPi(label_3D['r_y'] - frustum_angle)\n        bin_number = getBinNumber(centered_r_y, NH=self.NH)\n        bin_center = getBinCenter(bin_number, NH=self.NH)\n        residual = wrapToPi(centered_r_y - bin_center)\n        label_BboxNet = np.zeros((11,), dtype=np.float32)\n        label_BboxNet[0:3] = np.dot(frustum_R, label_3D['center']) - self.centered_frustum_mean_xyz\n        label_BboxNet[3] = label_3D['h']\n        label_BboxNet[4] = label_3D['w']\n        label_BboxNet[5] = label_3D['l']\n        label_BboxNet[6] = bin_number\n        label_BboxNet[7] = residual\n        label_BboxNet[8:] = self.mean_car_size\n        Rmat = np.asarray([[math.cos(residual), 0, math.sin(residual)], [0, 1, 0], [-math.sin(residual), 0, math.cos(residual)]], dtype='float32')\n        center = label_BboxNet[0:3]\n        l = label_3D['l']\n        w = label_3D['w']\n        h = label_3D['h']\n        p0 = center + np.dot(Rmat, np.asarray([l / 2.0, 0, w / 2.0], dtype='float32').flatten())\n        p1 = center + np.dot(Rmat, np.asarray([-l / 2.0, 0, w / 2.0], dtype='float32').flatten())\n        p2 = center + np.dot(Rmat, np.asarray([-l / 2.0, 0, -w / 2.0], dtype='float32').flatten())\n        p3 = center + np.dot(Rmat, np.asarray([l / 2.0, 0, -w / 2.0], dtype='float32').flatten())\n        p4 = center + np.dot(Rmat, np.asarray([l / 2.0, -h, w / 2.0], dtype='float32').flatten())\n        p5 = center + np.dot(Rmat, np.asarray([-l / 2.0, -h, w / 2.0], dtype='float32').flatten())\n        p6 = center + np.dot(Rmat, np.asarray([-l / 2.0, -h, -w / 2.0], dtype='float32').flatten())\n        p7 = center + np.dot(Rmat, np.asarray([l / 2.0, -h, 

In [7]:
df = pd.DataFrame()
labeled_data_verified = labeled_data[labeled_data['verified']==True]
df['code'] = labeled_data_verified['path'].apply(lambda x: load_code(x))
df['label'] = labeled_data_verified['verified_pattern'].values
df['file'] = labeled_data_verified['file'].values
df['code_summary'] = labeled_data_verified['code_summary'].values
df.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_verified_data.csv', index=False)

/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_3.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/3DOD_thesis/cluster_9.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_11.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_14.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_15.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_16.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_17.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_19.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_21.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_23.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_24.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_25.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_26.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_27.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_28.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_29.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_3.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_30.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_32.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_33.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_34.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_35.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_36.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_37.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_38.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_7.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AIlice/cluster_9.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_11.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_13.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_18.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_19.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_20.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_3.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_7.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/AgentBench/cluster_9.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ArxivDigest/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ArxivDigest/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_12.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_14.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_16.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_17.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_18.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_7.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Automatic_Speech_Recognition/cluster_9.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_7.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CAAFE/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CAAFE/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CAAFE/cluster_3.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CAAFE/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_103.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_106.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_107.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_114.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_12.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_124.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_139.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_142.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_143.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_146.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_159.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_161.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_41.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_50.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_51.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_53.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_63.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_67.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_76.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_79.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_8.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_84.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_92.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_96.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/ChatSim/cluster_97.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Copilot-Agent-365/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Copilot-Agent-365/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/Copilot-Agent-365/cluster_4.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CyberScraper-2077/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/CyberScraper-2077/cluster_7.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_0.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_100.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_109.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_110.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_112.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_113.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_116.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_121.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_16.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_18.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_2.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_21.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_24.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_26.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_28.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_31.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_32.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_33.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_36.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_37.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_38.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_39.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_40.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_47.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_48.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_62.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_65.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_70.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_71.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DLTA-AI/cluster_91.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DRL-Pytorch/cluster_5.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/DRL-Pytorch/cluster_6.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_1.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_10.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_12.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_13.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_16.py
/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/repo_callgraph_clusters/EvoAgentX/cluster_17.py

In [1]:
import pandas as pd
df = pd.read_csv('/home/hasinthaka/Downloads/wandb_export_2026-02-05T07_49_48.241+05_30.csv')

In [2]:
df

,class,precision,recall,f1-score,support
0,Agent Architecture,0.750000,0.600000,0.666667,20.000000
1,Forecasting with Classical Models,0.750000,0.609375,0.672414,64.000000
2,LLM-based Multimodal Generative Prompting,0.606557,0.711538,0.654867,52.000000
3,Model Abstraction,0.437500,0.700000,0.538462,20.000000
4,Preprocessing Text and Numerical Data,0.500000,0.568627,0.532110,51.000000
5,Retrieval Augmented Generation(RAG),0.769231,0.714286,0.740741,28.000000
6,Using Tools with LLMs,0.695652,0.516129,0.592593,31.000000
7,none,0.532258,0.515625,0.523810,64.000000
8,accuracy,0.606061,0.606061,0.606061,0.606061
9,macro avg,0.630150,0.616948,0.615208,330.000000
10,weighted avg,0.624119,0.606061,0.608978,330.000000

In [11]:
import pandas as pd

df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/ms_community_descriptions.csv')
df.drop(columns=['code'], inplace=True)
df.rename(columns={'description': 'code_summary'}, inplace=True)
df['file'] = df['file'].apply(lambda x: x.replace('https://github.com/HasinthakaPiyumal/AI-Pattern-Mining-Projectresult/ms_repo_callgraph_clusters/', 'https://github.com/HasinthakaPiyumal/AI-Pattern-Mining-Project/tree/main/notebooks/result/ms_repo_callgraph_clusters/'))

In [13]:
df.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/ms_community_descriptions_formatted.csv', index=False)

In [12]:
df.iloc[0]['file']

'https://github.com/HasinthakaPiyumal/AI-Pattern-Mining-Project/tree/main/notebooks/result/ms_repo_callgraph_clusters/saigonparking_java/cluster_11.java'

In [16]:
df.sample(50).to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/ms_community_descriptions_formatted_sample_01.csv', index=False)

### Split dataset

In [19]:
import pandas as pd
data = pd.read_csv('/home/hasinthaka/Downloads/emb-dataset-F2LLM-4B.csv')

num_cols = [col for col in data.columns if col.startswith('emb_')]
embeddings = data[num_cols]
data = data.drop(columns=num_cols)
data.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
embeddings['file'] = data['file']

import os
data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/metadata.csv', index=False)
embeddings.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/embeddings.csv', index=False)

/tmp/ipykernel_96840/267577299.py:2: DtypeWarning: Columns (2563,2564) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/home/hasinthaka/Downloads/emb-dataset-F2LLM-4B.csv')

In [20]:
data

,file,code_summary,label,verified
0,https://github.com/HasinthakaPiyumal/AI-Patter...,This Java file is a JUnit 4 test class (`Verif...,Other,True
1,https://github.com/HasinthakaPiyumal/AI-Patter...,This Spring Boot `@ConfigurationProperties` cl...,Other,True
2,https://github.com/HasinthakaPiyumal/AI-Patter...,This code defines a `User` JPA entity that imp...,Microservices Security,True
3,https://github.com/HasinthakaPiyumal/AI-Patter...,This code defines a custom Spring `AsyncConfig...,Microservices Observerbility,True
4,https://github.com/HasinthakaPiyumal/AI-Patter...,This code configures a Spring AOP advisor and ...,Microservices Observerbility,True
...,...,...,...,...
1105,https://github.com/HasinthakaPiyumal/AI-Patter...,This Python file defines client classes (`Prod...,NaN,NaN
1106,https://github.com/HasinthakaPiyumal/AI-Patter...,"This Flask route handles user registration, pr...",NaN,NaN
1107,https://github.com/HasinthakaPiyumal/AI-Patter...,This Flask frontend code defines routes for an...,NaN,NaN
1108,https://github.com/HasinthakaPiyumal/AI-Patter...,"This Python function, `service_row`, construct...",NaN,NaN
1109,https://github.com/HasinthakaPiyumal/AI-Patter...,This Python code defines functions to generate...,NaN,NaN

In [1]:
### Split to two

In [49]:
import pandas as pd

labeled = pd.read_csv("/home/hasinthaka/Downloads/AI Pattern Project_ Results - ms-pttn-100-v4.csv")
old_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/metadata-v3.csv')

new_data_map = {file:label for file, label in zip(labeled['file'], labeled['Pattern'])}
new_data = old_data.copy()
new_data['label'] = new_data['file'].apply(lambda x: new_data_map[x] if x in new_data_map else new_data[new_data['file']==x]['label'].values[0])
new_data['verified'] = new_data['label'].notna()
new_data['label'] = new_data['label'].apply(lambda x: x if x!='Service Implementation' else 'Business Logic')
new_data['label'] = new_data['label'].apply(lambda x: x if x!='Domain-driven design' else 'Data Model/ Domain design')
new_data['label'] = new_data['label'].apply(lambda x: x if x!='Transaction' else 'Transactions/Saga')
new_data['label'] = new_data['label'].apply(lambda x: x if x!='Saga' else 'Transactions/Saga')

In [50]:
new_data.to_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/notebooks/result/metadata-v4.csv', index=False)

In [13]:
new_data.head()

,file,code_summary,label,verified
0,https://github.com/HasinthakaPiyumal/AI-Patter...,This Java file is a JUnit 4 test class (`Verif...,Other,True
1,https://github.com/HasinthakaPiyumal/AI-Patter...,This Spring Boot `@ConfigurationProperties` cl...,Other,True
2,https://github.com/HasinthakaPiyumal/AI-Patter...,This code defines a `User` JPA entity that imp...,Microservices Security,True
3,https://github.com/HasinthakaPiyumal/AI-Patter...,This code defines a custom Spring `AsyncConfig...,Microservices Observerbility,True
4,https://github.com/HasinthakaPiyumal/AI-Patter...,This code configures a Spring AOP advisor and ...,Microservices Observerbility,True

In [51]:
new_data['label'].value_counts()

label
Microservices Security          61
Business Logic                  61
Other                           58
Data Model/ Domain design       47
Microservices Test              36
EDA                             27
Backends for Frontends          12
Database with Microservices     11
Microservices Observerbility     7
Transactions/Saga                5
CQRS                             4
API Gateway                      3
Service Discovery Pattern        1
Microservice Scaling             1
CICD                             1
Microservices UI                 1
Name: count, dtype: int64